version: "3.7"

services:
  nginx-web:
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX_WEB:-nginx-web}
    restart: always
    environment: 
      VIRTUAL_HOST: voice1.owwo.io
      LETSENCRYPT_HOST: voice1.owwo.io
      LETSENCRYPT_EMAIL: admin@owwo.io
    ports:
      - "${IP:-0.0.0.0}:${DOCKER_HTTP:-80}:80"
      - "${IP:-0.0.0.0}:${DOCKER_HTTPS:-443}:443"
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: ${NGINX_WEB_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup ${NGINX_WEB:-nginx-web} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN:-nginx-gen}
    restart: always
    environment:
      SSL_POLICY: ${SSL_POLICY:-Mozilla-Intermediate}
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${NGINX_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN:-nginx-gen}
      NGINX_PROXY_CONTAINER: ${NGINX_WEB:-nginx-web}
    logging:
      driver: ${NGINX_LETSENCRYPT_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE:-10}

  sfu:
    image: pionwebrtc/ion-sfu:latest
    build:
      dockerfile: ./docker/sfu.Dockerfile
      context: .
    volumes:
      - "./configs/docker/sfu.toml:/configs/sfu.toml"
    ports:
      - "5000-5200:5000-5200/udp"
    depends_on:
      - nats
      - etcd
      - nginx-letsencrypt
    networks:
      - ionnet

  biz:
    image: pionwebrtc/ion-biz:latest
    environment:
      VIRTUAL_PORT: 8443
      VIRTUAL_HOST: voice1.owwo.io
      LETSENCRYPT_HOST: voice1.owwo.io
      LETSENCRYPT_EMAIL: admin@owwo.io
    build:
      dockerfile: ./docker/biz.Dockerfile
      context: .
    volumes:
      - "./configs/docker/biz.toml:/configs/biz.toml"
      - ${NGINX_FILES_PATH:-./data}/certs/default.key:/configs/certs/default.key
      - ${NGINX_FILES_PATH:-./data}/certs/default.cert:/configs/certs/default.cert
    ports:
      - 8443:8443
    networks:
      - ionnet
    depends_on:
      - nats
      - etcd
      - nginx-letsencrypt

  islb:
    image: pionwebrtc/ion-islb:latest
    build:
      dockerfile: ./docker/islb.Dockerfile
      context: .
    volumes:
      - "./configs/docker/islb.toml:/configs/islb.toml"

    depends_on:
      - nats
      - etcd
      - redis
      - nginx-letsencrypt
    networks:
      - ionnet

  avp:
    image: pionwebrtc/ion-avp:latest
    build:
      dockerfile: ./docker/avp.Dockerfile
      context: .
    volumes:
      - "./configs/docker/avp.toml:/configs/avp.toml"
      - "./:/out/"
    depends_on:
      - nats
      - etcd
      - nginx-letsencrypt
    networks:
      - ionnet

  nats:
    image: nats
    ports:
      - 4223:4222
    networks:
      - ionnet

  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.9
    entrypoint: "/usr/local/bin/etcd"
    command: "--listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379"
    ports:
      - 2389:2379
    networks:
      - ionnet

  redis:
    image: redis:5.0.9
    ports:
      - 6380:6379
    networks:
      - ionnet

networks:
  ionnet:
    external: true
    name: ionnet
    driver: bridge
